steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "eu.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}",
        ".",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "eu.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}",
      ]

  # Deploy the image to be the latest revision of Cloud Run (NOT serve traffic yet)
  # The revision URL e.g. https://pr-1---myservice.run.app is ONLY AVAILABLE in Cloud Build's logs
  # So we need to link that URL back to the GitHub PR page in the next step
  - id: "deploy revision with tag"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--image",
        "eu.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}",
        "--tag",
        "pr-${_PR_NUMBER}",
        # Do not use this latest revision to serve traffic
        "--no-traffic",
      ]

  # The custom builder source code is in https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/run/deployment-previews
  # We have to built in manually and push it to the project's repository before running this build step
  - id: "link revision on pull request"
    name: "eu.gcr.io/${PROJECT_ID}/deployment-previews" # our custom builder
    secretEnv: ["GITHUB_TOKEN"]
    # The default command is python3 app/check_status.py in which check_status.py could be found in https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/run/deployment-previews
    args:
      [
        "set",
        "--project-id",
        "${PROJECT_ID}",
        "--region",
        "${_REGION}",
        "--service",
        "${_SERVICE_NAME}",
        "--pull-request",
        "${_PR_NUMBER}",
        "--repo-name",
        "${_GITHUB_REPO}",
        "--commit-sha",
        "${SHORT_SHA}",
      ]

substitutions:
  _SERVICE_NAME: fitnessbackend
  _GITHUB_REPO: $(pull_request.pull_request.head.repo.full_name)

options:
  dynamicSubstitutions: true

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"