version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    container_name: backend
    ports:
      - '3000:3000'
    volumes:
      # Do not map to node_modules inside the container
      - /app/node_modules
      - .:/app
      