apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: vinhlee95/fitness-backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
profiles:
  - name: development
    deploy:
      kustomize:
        paths:
          - kubernetes/base
  - name: production
    deploy:
      kustomize:
        paths:
          - kubernetes/overlay/production

