apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kustomize:
    paths:
      - kubernetes
build:
  local:
    push: false
  artifacts:
    - image: vinhlee95/fitness-backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .