apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: fitness-backend
        image: vinhlee95/fitness-backend:latest
        resources:
          # the container is limited to 1 CPU and 256MiB of memory, 
          # and requires at least 0.5 CPUs and 128MiB of memory.
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi"