apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-backend
spec:
  selector:
    matchLabels:
      app: fitness-backend
  template:
    metadata:
      labels:
        app: fitness-backend
    spec:
      containers:
      - name: fitness-backend
        image: vinhlee95/fitness-backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.1"
        ports:
        - containerPort: 3000
